#define MAX_WRITE_SIZE 256
#define MAX_STRING_SIZE 40
#define MAX_JOB_FILE_NAME_SIZE 256
#define MAX_PIPE_NAME_SIZE 40
#define MAX_KEY_NAME_SIZE 41
#define S 8
#define TEMP_FOLDER "/tmp/"
#define RESPONSE_CONNECT_DISCONNECT_SIZE 4